name: fieldr_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  firebase_database: ^11.2.0
  flutter_bloc: 9.0.0
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  golden_toolkit: ^0.15.0
  firebase_core_platform_interface: ^5.4.0
  firebase_auth_platform_interface: ^7.5.0
  fake_cloud_firestore: ^3.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
  - images/
