<<<<<<< HEAD
name: fieldr_project
=======
name: fieldr
>>>>>>> 16c78ab469d37117aeab4818438245c958c6ca08
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
<<<<<<< HEAD
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  firebase_database: ^11.2.0
  flutter_bloc: ^8.1.6
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  golden_toolkit: ^0.15.0
=======
  flutter:
    sdk: flutter
>>>>>>> 16c78ab469d37117aeab4818438245c958c6ca08

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
<<<<<<< HEAD
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true
  assets:
  - images/
=======

flutter:
  uses-material-design: true
>>>>>>> 16c78ab469d37117aeab4818438245c958c6ca08
