// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt0hwzUAdNpe1vyVFrCICN0rFU9xUDaRg',
    appId: '1:266205554078:web:b21cae1e214294b212228f',
    messagingSenderId: '266205554078',
    projectId: 'appdevfinalproj-5a190',
    authDomain: 'appdevfinalproj-5a190.firebaseapp.com',
    storageBucket: 'appdevfinalproj-5a190.firebasestorage.app',
    measurementId: 'G-PRFYKV9XMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0WbE0e6A7wX4J4negzB1f4Q93aP2vvc',
    appId: '1:266205554078:android:b47782ea032244c912228f',
    messagingSenderId: '266205554078',
    projectId: 'appdevfinalproj-5a190',
    storageBucket: 'appdevfinalproj-5a190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlptesFc8XskhNfpIrkmEIwALa62643_k',
    appId: '1:266205554078:ios:9f4680e927c3611812228f',
    messagingSenderId: '266205554078',
    projectId: 'appdevfinalproj-5a190',
    storageBucket: 'appdevfinalproj-5a190.firebasestorage.app',
    androidClientId: '266205554078-ss2307a4u3vef4bp2c0pt9k1u97io6lt.apps.googleusercontent.com',
    iosClientId: '266205554078-ovqgst73jbfn9sbmtordhqpotifd3k1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fieldrProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt0hwzUAdNpe1vyVFrCICN0rFU9xUDaRg',
    appId: '1:266205554078:web:dcd7ba02557ac9d912228f',
    messagingSenderId: '266205554078',
    projectId: 'appdevfinalproj-5a190',
    authDomain: 'appdevfinalproj-5a190.firebaseapp.com',
    storageBucket: 'appdevfinalproj-5a190.firebasestorage.app',
    measurementId: 'G-4S2L9WGCGH',
  );

}